version: "2.1"
services:
  asterisk:
    build: .
    container_name: asterisk
    environment:
      - PUID=1000
    volumes:
      - config/asterisk:/etc/asterisk
      - /run/udev:/run/udev:ro
      - /dev:/dev
      - logs/asterisk:/var/log/asterisk
    #ports:
    #  - "5060:5060/udp"
    #  - "10000-10005:10000-10005/udp"
    # https://github.com/docker/compose/issues/9085
    network_mode: host
    restart: unless-stopped
    # https://stackoverflow.com/a/62758958
    device_cgroup_rules: ["c 188:* rmw"]
    
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config/fail2ban:/config
      - logs/asterisk:/remotelogs/asterisk:ro
      #- /var/log:/var/log:ro
    restart: unless-stopped    
    
volumes:
  config:
  logs:
