version: "2.1"
services:
  asterisk:
    build: .
    container_name: asterisk
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:        
     # - type: volume
     #   source: config
     #   target: /etc/asterisk    
      - config:/etc/asterisk
      - log:/var/log/asterisk
      - /run/udev:/run/udev:ro
      - /dev:/dev
    #ports:
    #  - "5060:5060/udp"
    #  - "10000-10005:10000-10005/udp"
    # https://github.com/docker/compose/issues/9085
    network_mode: host
    restart: unless-stopped
    # https://stackoverflow.com/a/62758958
    device_cgroup_rules: ["c 188:* rmw"]
          
volumes:
  config:
  log:
