version: "2.1"
services:
  asterisk:
    build: .
    container_name: asterisk
    environment:
      - PUID=1000
    volumes:
      - config:/etc/asterisk
      - /run/udev:/run/udev:ro
      - /dev:/dev
    ports:
      - "5060:5060/udp"
    #  - "10000-20000/udp"
    restart: unless-stopped
    # https://stackoverflow.com/a/62758958
    device_cgroup_rules: ["c 188:* rmw"]
    
volumes:
  config:
